spring:
  application:
    name: wedding
  datasource:
    url: jdbc:postgresql://cet8gijgk7sjl9.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com/daff9jrtkd4f0i
    username: ue3acac1n3svpo
    password: pb94ba61ca4e9995700443ec5b2375c1949fd410fc44e5257f92cb96ff60c4eed
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          driver_class: org.postgresql.Driver
        format_sql: false
    hibernate:
      ddl-auto: update
    show-sql: false