spring:
  application:
    name: wedding
  datasource:
    url: jdbc:postgresql://cer3tutrbi7n1t.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com/d18die82fbfn4m
    username: uau78uasrivrtt
    password: p4d26306128f4852c2792804b1eba3f1380b6835b0f3143318d7192339374767c
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          driver_class: org.postgresql.Driver
        format_sql: false
    hibernate:
      ddl-auto: update
    show-sql: false